### ISSUE TITLE
Getting 'command not found' error on Fedora 34

### ISSUE THREAD

**Issue by praneetk96** [anhsirk0/fetch-master-6000#14]
I followed every step as it is and when i run it, i am getting an error message `sh: line 1: dpkg-query: command not found` along with the fm6000 output. i'm also attaching a screenshot of the error.
![fm6000_error_fedora_34](https://user-images.githubusercontent.com/39919187/117303464-563d8100-ae9a-11eb-9bbd-471d6e5d9574.png)

**Comment by anhsirk0** [comment]
Thanks for reporting , its because I forget to redirect errors to dev null
I will fix it right now

**Comment by anhsirk0** [comment]
Fixed it 
Also you can install via the installer script (only one step)
Thanks

**Comment by praneetk96** [comment]
Thank you so much man!! for fixing it! now it's perfect!
