### ISSUE TITLE
Use `dpkg-query` instead of `apt`.

### ISSUE THREAD

**Issue by shivanshu-semwal** [anhsirk0/fetch-master-6000#2]
https://github.com/anhsirk0/fetch-master-6000/blob/44d8a4f2b1d843d7a6aeaab90f2113fc56f90dfd/fm6000.pl#L60

This spits out following error `WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`. 
I think the solution might be either to redirect the error to `/dev/null` or to use `dpkg-query` which both `neofetch` and `pfetch` use.

`dpkg-query -f '\n' -W'` or `dpkg-query -W -f='${binary:Package}\n'`

But there was slight difference between `apt list --installed | wc -l` and `dpkg-query -f '\n' -W | wc -l`.

I did `man apt` and found this, but I can't figure out how to get the `apt list --installed` functionality using `apt-get` or `apt-cache`.
```
The apt(8) commandline is designed as an end-user tool and it
       may change behavior between versions. While it tries not to
       break backward compatibility this is not guaranteed either if
       a change seems beneficial for interactive use.

       All features of apt(8) are available in dedicated APT tools
       like apt-get(8) and apt-cache(8) as well.  apt(8) just
       changes the default value of some options (see apt.conf(5)
       and specifically the Binary scope). So you should prefer
       using these commands (potentially with some additional
       options enabled) in your scripts as they keep backward
       compatibility as much as possible.
```

**Comment by anhsirk0** [comment]
Thanks !!
It was dpkg-query initially
but it didnt worked on a Ubuntu machine
I will use one these now
dpkg-query -f '\n' -W' or dpkg-query -W -f='${binary:Package}\n'

Thanks again
