### ISSUE TITLE
improve script

### ISSUE THREAD

**Issue by arcolinuxz** [anhsirk0/fetch-master-6000#23]
https://github.com/anhsirk0/fetch-master-6000/blob/2f185705f0a0a075e87ffe493cc2db40f3fc73d9/install.sh#L41

Move this line after line where you install it line 36

I said NO do not install and it says installed to me
nice project by the way
love dilbert

**Comment by anhsirk0** [comment]
Sure thing !!
Also I am a huge fan of your work (Arcolinux and your youtube channel)

**Comment by anhsirk0** [comment]
I added an exit command right after no situation

**Comment by arcolinuxz** [comment]
thanks for the support
