### ISSUE TITLE
sh: line 1: dpkg-query: command not found

### ISSUE THREAD

**Issue by Rashad-707** [anhsirk0/fetch-master-6000#24]
I'm getting this error `sh: line 1: dpkg-query: command not found` and after this line there is the normal output of the script, how can i get rid of this error.
 
![Screenshot_20210827_164329](https://user-images.githubusercontent.com/61148691/131136895-6996aa50-d6d0-4561-ba20-3da227be6de9.png)

**Comment by anhsirk0** [comment]
Thanks for reporting , its fixed now,
Somehow I missed to send the errors to /dev/null on this one

**Comment by Rashad-707** [comment]
Thank you, it works great now :)
