### ISSUE TITLE
I don't use pacman

### ISSUE THREAD

**Issue by mauro-balades** [anhsirk0/fetch-master-6000#28]
This is what happens when you use Pacman in ubuntu:

![3hq6Hml](https://user-images.githubusercontent.com/91018726/147466626-71ae6ee7-6fc6-4f7e-987f-8f5024cdc6a4.png)

**Comment by mauro-balades** [comment]
Update: 
I had run `sudo apt-get remove pacman` and it works now...

**Comment by anhsirk0** [comment]
`fm6000` first try to check if `pacman` is available to count packages for Arch based distros.
For now I've changed the order of checking packages.
You can now install pacman.

**Comment by mauro-balades** [comment]
in KDE (idk about other distros) pacman just opens a game...

**Comment by anhsirk0** [comment]
pacman is a game on some distros , i didn't know that. The name conflicts with the arch package manager.

**Comment by anhsirk0** [comment]
I have updated the fm6000.pl, you can now re-install it , i am closing this issue
