### ISSUE TITLE
Issue using script

### ISSUE THREAD

**Issue by OlaoluwaM** [anhsirk0/fetch-master-6000#32]
I get this error

![image](https://user-images.githubusercontent.com/37044906/156928860-40a95c05-6f9f-4110-a9d1-30e26bbfaab9.png)

## Sys Info
OS: Fedora 35
Perl Version: 5.34

**Comment by anhsirk0** [comment]
This looks like Experimental module is not intalled on your OS (Its pre-installed on most of the distros)
I will look into it, till then you can comment these lines to get it working.

line 10
`use experimental 'smartmatch';`
line 243-245
` if ($de ~~ @wm) {
        $de_placeholder = 'WM';
    }`

**Comment by anhsirk0** [comment]
Is your OS up to date?

**Comment by OlaoluwaM** [comment]
Yes!

![image](https://user-images.githubusercontent.com/37044906/157418625-359bc0eb-9e49-4460-a8b3-1c0616082557.png)

**Comment by opalmay** [comment]
Had the same issue, this fixed it for me:
`sudo dnf install perl-experimental`

**Comment by OlaoluwaM** [comment]
Yeah, that fixed it! @anhsirk0 consider adding that to the docs?
