### ISSUE TITLE
Number of Packages is unknown (openSUSE)

### ISSUE THREAD

**Issue by rstreeter** [anhsirk0/fetch-master-6000#33]
No matter what I try and add to show the number of packages it always comes up with unknown
![Screenshot_20220306_123830](https://user-images.githubusercontent.com/500779/156937465-363de0c8-2d82-48c2-b27b-44688e6f8ddf.jpeg)
. I am using a custom command for customization in my bashrc.
I was wondering if there was a way to add the package count manually to the command in openSUSE?

**Comment by anhsirk0** [comment]
yes you can with:
`fm6000 -package 1234`

in your case:
`fm6000 -package $(rpm -qa)`

**Comment by anhsirk0** [comment]
I will add packages count for opensuse.

**Comment by anhsirk0** [comment]
packages added to the script.

**Comment by rstreeter** [comment]
Thank you
