### ISSUE TITLE
uptime reporting incorrect

### ISSUE THREAD

**Issue by irishwoody** [anhsirk0/fetch-master-6000#34]
![image](https://user-images.githubusercontent.com/2574396/161521275-5d616a98-3032-4218-bd55-0f0ab68264e2.png)

**Comment by anhsirk0** [comment]
can you post a screenshot of uptime
```bash
$ uptime
```

**Comment by irishwoody** [comment]
![image](https://user-images.githubusercontent.com/2574396/162188300-bf0259a7-476b-47ad-a7cb-db3b308eaee5.png)

Looks like it was working at moment..  Could be that day 4 with zero hours - the code does not pick up the zero hours ? Does uptime report "4 days, 18 minutes" or "4 days, 0 hours, 18 minutes" ?

**Comment by anhsirk0** [comment]
uptime reports 4 days, 18 minutes. Thats what causing problem
I am formatting uptime wrongly.
I am fixing it right  now.

**Comment by anhsirk0** [comment]
Fixed via #35
