### ISSUE TITLE
Support for ascii art in random option

### ISSUE THREAD

**Issue by pineapples5972** [anhsirk0/fetch-master-6000#37]
It should be great to be able to provide directory of random ascii art text files and -r flag could randomly shuffle them

**Comment by anhsirk0** [comment]
Thats a nice idea, I will try to add it as soon as possible.

**Comment by pineapples5972** [comment]
Actually I was thinking if there is possibility to use both -r and -f flag together, so it would randomly able to generate both inbuilt artworks and external artworks together.

**Comment by anhsirk0** [comment]
Makes sense

**Comment by anhsirk0** [comment]
In the mean time use this bash script to emulate similar behavior.
```bash
#!/usr/bin/env bash

if [ ! -d "$1" ]; then
    echo "Please provide a Directory"
    exit
fi

files=( $(ls $1 -p | grep -v /) )
random_file_num=$(($RANDOM % ${#files[@]}))

fm6000 -f "$1/${files[$random_file_num]}"

```

**Comment by anhsirk0** [comment]
I added the feature , I couldn't combine `-r` and `-f` , instead it should be specified via `-rd` or `--random-dir`
`fm6000 -rd "ascii_arts"`

**Comment by pineapples5972** [comment]
Thanks. Its convenient and also feels like unix way to have artworks available in seperate folder. 
I like that new fish one. btw. 🐠
