### ISSUE TITLE
unable to detect DE or WM

### ISSUE THREAD

**Issue by pineapples5972** [anhsirk0/fetch-master-6000#43]
I used fm6000 in several wms exclusively dwm, xmonad, openbox
and everytime it shows `de UNKNOWN` so i have to use -de flag and specify manually which wm i am currently using.
However I did some research and found that wmctrl can be useful to detect current wm.

```
sub get_de {
    my $de = $ENV{DESKTOP_SESSION};
    unless ($de) { $de = $ENV{XDG_SESSION_DESKTOP}
}
    unless ($de) { $de = $ENV{XDG_CURRENT_DESKTOP}
}
    unless ($de) { $de = `wmctrl -m | grep Name | awk '{print $2}' `}
    unless ($de) { $de = "Unknown" }
    return $de;
}

```

Here I tried to use it in my noobie way but I unable to get rid of trailing new line it gives at the end.
`wmctrl -m | grep Name | awk '{print $2}' `
I know implementing wmctrl might add to another dependancy stack but i think its worth it.

I hope you'd find some fix for it.

**Comment by anhsirk0** [comment]
I will see about that.
I will lookup how neofetch does it, and implement that here.

**Comment by XDream8** [comment]
xprop can be used too, but i think the best would be checking the running processes for window managers(pfetch uses this method as a fallback to xprop)

**Comment by anhsirk0** [comment]
yeah neofetch does that too `ps` and `grep`ing.
I will implement that soon.

**Comment by pineapples5972** [comment]
@anhsirk0 Instead of using complicated functions why not just use wmctrl if its giving direct result?

**Comment by XDream8** [comment]
> @anhsirk0 Instead of using complicated functions why not just use wmctrl if its giving direct result?

It is very easy to add support for wmctrl or xprop but when we can implement it in perl, why should we prefer an external program?

**Comment by anhsirk0** [comment]
> > @anhsirk0 Instead of using complicated functions why not just use wmctrl if its giving direct result?
> 
> It is very easy to add support for wmctrl or xprop but when we can implement it in perl, why should we prefer an external program?

Exactly.

**Comment by pineapples5972** [comment]
Even tho its not minimal? ok doesnt matter.

**Comment by anhsirk0** [comment]
I updated the script. can you confirm?

**Comment by anhsirk0** [comment]
> Even tho its not minimal? ok doesnt matter.

we don't want unneccessary dependencies and prefer to do things with the language (perl in this case) rather than using external program. This increases portability (bsd's core util and gnu core utils are not that compatible , for example uptime gnu supports `uptime -p` while bsd does not. We are even avoiding to use `grep` or `awk` for the same reason.

**Comment by pineapples5972** [comment]
> I updated the script. can you confirm?

Yes it shows dwm correctly but in openbox it showing UNKNOWN

**Comment by anhsirk0** [comment]
added openbox to the checks too

**Comment by pineapples5972** [comment]
> added openbox to the checks too

So this is how it gonna be? you just add the new wm to array? 
Isnt there any functional way to "just detect current wm" using perl?

**Comment by anhsirk0** [comment]
> > added openbox to the checks too
> 
> So this is how it gonna be? you just add the new wm to array? Isnt there any functional way to "just detect current wm" using perl?

Sadly no
Neofetch/pfetch also does it in similar ways

**Comment by anhsirk0** [comment]
I added `wmctrl` too.

**Comment by pineapples5972** [comment]
Nice. Sometime we need to improvise even if its add another dependancy. but thats the beauty of perl language we can beautifully integrate unix shell with it.

**Comment by anhsirk0** [comment]
Well I was slightly wrong about external dependencies. Its not like `fm6000` won't work without `wmctrl` or `ps` etc etc.
