### ISSUE TITLE
How to set a random character?

### ISSUE THREAD

**Issue by diorcula** [anhsirk0/fetch-master-6000#52]
I edited the file so that `my $color='random` but would also like to do this for the character displayed.

Could not find how to do this, any idea?

**Comment by anhsirk0** [comment]
do you mean `fm6000 -r`?
if you want to edit file
```perl
my $random = true;
```

**Comment by diorcula** [comment]
ah yes totally meant that!
will do that, thanks a lot :)

**Comment by diorcula** [comment]
ah yes totally meant that!
will do that, thanks a lot :)

**Comment by anhsirk0** [comment]
for random color you can use
`fm6000 -c "random"`
