### ISSUE TITLE
Uptime is wrong and shows that there is an invalid option

### ISSUE THREAD

**Issue by Hacker-Planet** [anhsirk0/fetch-master-6000#54]
When I use fm6000 it shows that the uptime option in it is invalid and when I do an uptime it shows the correct output, but in fm6000 it shows me the local time as my uptime.
![Screenshot_20230412_170944](https://user-images.githubusercontent.com/500779/231598019-6715ceb9-4a53-4e7c-9ecc-bdc28b845387.png)
![Screenshot_20230412_171202](https://user-images.githubusercontent.com/500779/231598028-a5d9f665-40c5-4b70-888f-28d7497c6c1e.png)

**Comment by Hacker-Planet** [comment]
![Screenshot_20230413_162633](https://user-images.githubusercontent.com/500779/231886683-dcfb5ddc-fdcc-4d78-beaa-7ce05216bdce.png)
Here is the output of those commands and the output of the uptime help
Is it possible to comment out the uptime part of fm6000 to completely disable that?

**Comment by anhsirk0** [comment]
It seems your `uptime` might be out of date (or a totally different program).

I will update fm6000 as soon as I figure out what to do for SUSE based Distros.
In the meantime you can use this to get uptime for `fm6000`.
```bash
fm6000 -u $(uptime | cut -f1 -d',' | sed 's/^.*up //')
```

I would recommend installing/updating `uptime` on your system.
For comparison `uptime` version on my system (Archman Linux)
```bash
$ uptime --version
uptime from procps-ng 3.3.17
```

If you want to completely disable uptime for `fm6000` you will have to modify the code.
You can edit these lines (around line number `356`)
```perl
    my $i = 0;
    $info[$i++] = ' ' x ($width + $gap + $margin);  # empty line
    $info[$i++] = $os;
    if ($vnstat eq '-1' ) { $info[$i++] = $ke; }
    $info[$i++] = $de;
    $info[$i++] = $sh;
    $info[$i++] = $up;  # uptime (make your changes here)
    $info[$i++] = $pac;
    unless ($vnstat eq '-1' ) { $info[$i++] = $usg }
    $info[$i++] = ' ' x ($width + $gap + $margin);
```
If you need any help regarding editing the code, feel free to ask.

**Comment by Hacker-Planet** [comment]
My uptime must be coming from GNU coreutils, here is my output of uptime --version ~ 04:53:09 PM ❱❱ uptime --version
uptime (GNU coreutils) 9.2
I have procps 3.17 installed, I am using openSUSE Tumbleweed so I would everything is up to date as possible as far as my OS goes.

**Comment by Hacker-Planet** [comment]
The string with the options seems to work fine, I already run it with a custom string of commands for customization purposes. So I just added the one you provided to mine and presto it seems to be working. Thank you for your help and hard work on this project.

**Comment by anhsirk0** [comment]
Thanks for the kind word. I updated the script it should show you correct uptime now.
Please get it from the repo on codeberg - https://codeberg.org/anhsirk0/fetch-master-6000
I will push it (here on github) later. 
Let me know if it works correctly.

**Comment by Hacker-Planet** [comment]
Thank you for the fix, the new script worked like a charm.
