### ISSUE TITLE
OpenBSD

### ISSUE THREAD

**Issue by rayit** [anhsirk0/fetch-master-6000#55]
Had some problems with OpenBSD support (made a fork).
Added following lines to get_uptime seems fixing it...

`sub get_uptime {
    my $seconds;
    my $now = time();
    # macOS
    if ($os eq "OSX") {
        my $boot = `sysctl -n kern.boottime`;
        ($boot) = $boot =~ /{ sec = (\d+)/;
        $seconds = $now - $boot;
    } elsif ($os eq "OpenBSD") {
        my $boot = `sysctl -n kern.boottime`;
        $seconds = $now - $boot;`

**Comment by XDream8** [comment]
if you are sure that ``sysctl -n kern.boottime`` gives uptime like Mac it is really easy to fix.

Changing this line should fix:
``if ($os eq "OSX")`` -> ``if ($os eq "OSX" || $os eq "OpenBSD")``

**Comment by XDream8** [comment]
@anhsirk0 should i open a pr

**Comment by rayit** [comment]
Changing 
if ($os eq "OSX") -> if ($os eq "OSX" || $os eq "OpenBSD")

Gives wrong value somehow: UPTIME    19503d, 139m

rayx1$ sysctl -n kern.boottime
1685088630
`
 my $boot = `sysctl -n kern.boottime`;
        $seconds = $now - $boot;
 `       
        But this seems working...

**Comment by anhsirk0** [comment]
If this is working for you then you should add it after line 180
```perl
        # For Linux/BSD
        if (open(FH, "<" . "/proc/uptime")) {
            chomp($seconds = <FH>);
            close(FH);
            $seconds =~ s/\.*$//;
            $seconds = int($seconds);
        } elsif ($OS =~ m/BSD/i) {
            # your code here
        } else {
            my $boot = `date -d "\$(uptime -s)" +%s`;
            $seconds = $now - $boot;
        }
```
I cannot verify it myself at the moment, So just create a PR , I will merge it asap.
@rayit , @XDream8
