### ISSUE TITLE
Random colours and characters

### ISSUE THREAD

**Issue by sigrdrifa** [anhsirk0/fetch-master-6000#6]
Hi there, love this script but would it be possible to add support for random colours and/or random character e.g. it picks a random ASCII character and random colours each time you run the script when you pass it a "--random" or "-r" flag or something?

**Comment by anhsirk0** [comment]
Random  is already available (-c random & -random)
fm6000 -c random    or   fm6000 -color random

fm6000 -r    or fm6000 -random
I added random arts option an hour ago but didnt added screen shot of it ( i just updated screenshots)
 
Thanks

**Comment by anhsirk0** [comment]
fm6000 -r -c random
for both random color and random art

**Comment by sigrdrifa** [comment]
Awesome, thanks!
