### ISSUE TITLE
WM not showing

### ISSUE THREAD

**Issue by gaurav219** [anhsirk0/fetch-master-6000#7]
I use "xmonad" but it does not show and instead is blank.

![2021-05-03_16:17:06](https://user-images.githubusercontent.com/44445154/116867644-26d50d00-ac2b-11eb-873f-92be89dd0ff9.png)

**Comment by anhsirk0** [comment]
what's the output when you run these commands
echo $XDG_CURRENT_DESKTOP
echo $XDG_SESSION_DESKTOP

In the mean time you can do
fm6000 -de "xmonad" -n
I saw Distrotube's video and he was using xmonad, fm6000 was detecting his WM correctly

**Comment by anhsirk0** [comment]
also check
echo $DESKTOP_SESSION

**Comment by anhsirk0** [comment]
the last one ($DESKTOP_SESSION) should shows xmonad
I updated fm6000 (added $DESKTOP_SESSION)
I hope this will fix it 
Please check and let me know

**Comment by gaurav219** [comment]
> the last one ($DESKTOP_SESSION) should shows xmonad
> I updated fm6000 (added $DESKTOP_SESSION)
> I hope this will fix it
> Please check and let me know

`$DESKTOP_SESSION` is xmonad.

```
$XDG_CURRENT_DESKTOP
$XDG_SESSION_DESKTOP
```

These two were empty. 

Anyways, really good script.

It works now!!

Thanks!!
